### ISSUE TITLE
Error with WorldeditRegions v0.2.9

### ISSUE THREAD

**Issue by MrSnowGlobe** [boy0001/WorldeditRegions#1]
Hi there!

I'm getting the following error:
http://pastebin.com/txvQswwN

The plugin loads without error.

Cheers,
Snow!

**Comment by boy0001** [comment]
The paste has been removed; Is it still an issue?

**Comment by MrSnowGlobe** [comment]
Shoot, I must of set the expire date on the paste bin too short.

It still is, it's the same error that CloudeLecaw reported on the bukitdev page.

Here's his paste bin link: http://pastebin.com/xLrm3phb

The plugin loads without error and the actual error doesn't show up until someone enters a WorldEdit Region

**Comment by boy0001** [comment]
Sorry for the late response, I've been really busy lately :/

The issue is caused by WorldEdit not being recognized by your version of WorldEditRegions. This could be caused by one (or more) of the following:
- Old version of WorldEdit, new version of WRG
- Dev build of WorldEdit, any version of WRG.
- Some other reason why WorldEdit isn't being detected.

If you are using the latest version of WorldEdit, could you send me your startup log, as well as the version of WorldEdit that you are using? 

Thanks for your patience, hopefully we can get the resolved.

**Comment by MrSnowGlobe** [comment]
No need to be sorry champ, 100% ok on my end (:

Here is my startup log - http://pastebin.com/VP8D8jaS

WE version - v6.0.2-SNAPSHOT;3347-fe6717a0

**Comment by MrSnowGlobe** [comment]
Friendly Bump

**Comment by boy0001** [comment]
Did you happen to reload the server using /reload
?

If so, that would be the source of the issue.

**Comment by MrSnowGlobe** [comment]
No I didn't

I had my dev look into the issue and it appears that WER isn't compatable with WorldGuard 6. A few parts of the API was changed, that is probably the source of the problem

**Comment by boy0001** [comment]
The latest version supports WorldGuard and WorldEdit 6. Are you sure the plugin is up to date?

**Comment by MrSnowGlobe** [comment]
Yes, using the latest builds

**Comment by MrSnowGlobe** [comment]
Can you tell me what builds you're running WER against?

**Comment by boy0001** [comment]
WER 1.0.1:
http://dev.bukkit.org/bukkit-plugins/wrg/files/34-v1-0-1/

WorldEdit 6 beta 2
WorldGuard 6 beta 2

**Comment by MrSnowGlobe** [comment]
So sorry for the delay!

Thankyou so much! After testing it appears to be functional again. I shall continue to do some more testing and get back to you (in a timely manner)
